# A lightweight image used for tests
FROM rust:1.90-slim

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  libssl-dev \
  pkg-config \
  git \
  curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY . /app

WORKDIR /app
